# Docker

# Build a Docker image locally

trigger: none
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Aqua
      inputs:
        command: login
        containerRegistry: aqua-register    

    - bash: |
        docker pull mongo:latest
        docker pull nginx:latest
      displayName: Pull Docker image

    - task: aquasecScanner@4
      inputs:
        image: 'mongo'
        scanType: 'local'
        register: false
        registry: false
        hideBase: false
        showNegligible: true
        connection: 'demo-2465'
        scanner: 'registry.aquasec.com/scanner:6.2.RC2'

    - task: aquasecScanner@4
      inputs:
        image: 'nginx'
        scanType: 'local'
        register: true
        hideBase: true
        showNegligible: false
        scanner: 'registry.aquasec.com/scanner:6.2'
        connection: 'demo-2465'
